In [19]:
import numpy as np
import pandas as pd
import csv
from sklearn import datasets
import sys
import data_preprocessing

In [20]:
data = pd.read_csv("./test_dataset/hill-valley.csv")

In [22]:
data = data_preprocessing.process_data(data)

In [23]:
data

,V89,V90,V91,V92,V93,V94,V95,V96,V97,V98,V99,V100,cls
0,37.13,37.47,37.57,36.62,36.92,38.80,38.52,38.07,36.73,39.46,37.50,39.10,0
1,1.79,1.78,1.71,1.80,1.79,1.77,1.74,1.74,1.80,1.78,1.75,1.69,1
2,75592.31,72895.84,69384.71,73438.88,71053.35,71112.62,74916.48,72571.58,66348.97,71063.72,67404.27,74920.24,1
3,47866.58,39834.12,47653.60,42625.67,40684.20,46960.73,44546.80,45410.53,47139.44,43095.68,40888.34,39615.19,0
4,5.29,5.82,5.52,5.17,5.67,5.60,5.94,5.73,5.22,5.30,5.73,5.91,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
506,508.10,533.32,475.70,439.04,518.21,498.18,482.78,504.60,483.94,534.39,527.98,508.49,1
507,57.23,58.72,58.14,55.55,59.35,56.45,62.02,57.85,62.64,57.05,58.62,58.55,0
508,48.83,48.77,45.64,49.20,49.83,49.09,48.39,52.08,51.90,50.36,48.41,46.98,0
509,381.33,385.83,392.77,361.36,366.62,379.56,405.16,369.41,360.07,387.82,382.21,382.49,0
510,418.85,437.26,408.78,414.18,407.73,404.12,434.66,404.63,436.27,427.26,427.66,410.97,1

In [31]:
# sys.path.insert(1, "/Volumes/Education-Imp/UOttawa Master's/Final_Project/METALLIC/Dataset")
# sys.path.insert(1, "C:/Ronald/uOttawa/6900/Metallic-main/Dataset")
def loading(file_name):
    d, ts = csv_loading(file_name)  # d is data, ts is targets

    return d, ts



def csv_loading(csv_name):
    '''
    Loading in CSV files
    :param csv_name: name of CSV file
    :return: Numpy array of data and targets,
            data: 2 dimensional numpy array with shape (x, y)
            targets: 1 dimensional numpy array with shape (x,)
    '''
    d, ts = [], []

    with open(csv_name) as csv_file:
        csv_reader = csv.reader(csv_file, delimiter=',')
        row_count = 0
        for row in csv_reader:
            try:
                if row_count == 0:
                    row_count += 1
                else:
                    temp_d = []
                    for i in range(len(row)):
                        if i < len(row) - 1:
                            try:
                                temp_d.append(float(row[i]))
                            except ValueError:
                                temp_d.append(float("nan"))
                        else:
                            try:
                                ts.append(int(row[i]))
                            except ValueError:
                                ts.append(float("nan"))

                    d.append(temp_d)
            except ValueError: # Skipping the lines with N/A or any other invalid values
                continue

    return np.array(d), np.array(ts)

In [27]:
filename = "./test_dataset/hill-valley.csv"

In [32]:
loading(filename)

<_csv.reader object at 0x000002854A62FFA0>

(array([[3.713000e+01, 3.747000e+01, 3.757000e+01, ..., 3.946000e+01,
         3.750000e+01, 3.910000e+01],
        [1.790000e+00, 1.780000e+00, 1.710000e+00, ..., 1.780000e+00,
         1.750000e+00, 1.690000e+00],
        [7.559231e+04, 7.289584e+04, 6.938471e+04, ..., 7.106372e+04,
         6.740427e+04, 7.492024e+04],
        ...,
        [4.883000e+01, 4.877000e+01, 4.564000e+01, ..., 5.036000e+01,
         4.841000e+01, 4.698000e+01],
        [3.813300e+02, 3.858300e+02, 3.927700e+02, ..., 3.878200e+02,
         3.822100e+02, 3.824900e+02],
        [4.188500e+02, 4.372600e+02, 4.087800e+02, ..., 4.272600e+02,
         4.276600e+02, 4.109700e+02]]),
 array([0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1,
        0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1,
        0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1,
        1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1,
        1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0,
        1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0,
        0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0,
        1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
        0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1,
        0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1,
        1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0,
        0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1,
        1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1,
        1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0,
        0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0,
        1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1,
        1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
        1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0,
        1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1,
        1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0,
        1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0,
        0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1,
        1, 0, 0, 0, 1]))